name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.build.outputs.version}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - id: build
        name: Build with Maven
        run: |
          mvn -B -ntp versions:set -DnewVersion=${{ github.event.release.tag_name }}
          mvn -B -V -ntp clean package  -DskipTests
          echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> "$GITHUB_OUTPUT"

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/components/packages/vinted-kafka-connect-vespa-${{ steps.build.outputs.version }}.zip
          tag: ${{ steps.build.outputs.version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vinted-kafka-connect-vespa-${{ steps.build.outputs.version }}
          path: |
            target/components/packages/vinted-kafka-connect-vespa-${{ steps.build.outputs.version }}.zip
            target/components/kafka-connect-vespa-${{ steps.build.outputs.version }}.jar
